version: '3.8'

services:
  # The Python Backend & Web Server
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Connect the API straight into the PostgreSQL networked container
      - DATABASE_URL=postgresql+psycopg://postgres:admin@db:5432/ai_costs
    depends_on:
      db:
        condition: service_healthy

  # The PostgreSQL Analytics Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ai_costs
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
